version: '3.9'
services:
  db:
    image: postgres:15.10-alpine
    container_name: next_train_db_cont
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data/
      - ./src/data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./src/data/populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PGUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod

  backend:
    image: whitenz/next_train:latest
    container_name: next_train_backend_cont
    volumes:
      - data_vol:/src/data/
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env.prod

volumes:
  db_vol:
  data_vol: